#!/bin/bash
# Build SquashFS app
set -e

BASEDIR="$(dirname "$0")"

if [[ $# -lt 1 || $# -gt 2 ]]; then
    echo >&2 "Usage: $0 <sourcedir> [<main>]"
    exit 2
fi

SOURCE="$1"
SQUASHAPP_NAME="$(basename "${SOURCE}")"
SQUASHAPP_MAIN="${2:-bin/${SQUASHAPP_NAME}}"
SQUASHAPP_SHELL=${SQUASHAPP_SHELL:-/bin/bash}
SQUASHAPP="${SQUASHAPP_NAME}.run"

if ! [[ -d "${SOURCE}" ]]; then
    echo >&2 "ERROR: ${SOURCE} is not a directory"
    exit 1
fi

if ! [[ -x "${SQUASHAPP_SHELL}" ]]; then
    echo >&2 "ERROR: ${SQUASHAPP_SHELL} is not a valid executable"
    exit 1
fi

if ! (cd "${SOURCE}" && [[ -n "$(find . -wholename ./"${SQUASHAPP_MAIN}" -executable)" ]]); then
    echo >&2 "ERROR: Could not find executable ${SQUASHAPP_MAIN} in ${1}"
    echo >&2 "Note: <main> must be relative to <dir> (e.g. \"bin/${SQUASHAPP_NAME}\")"
    exit 1
fi

# Build SquashFS
SQUASHFS="${SQUASHAPP_NAME}.squash"

echo >&2 "Building ${SQUASHFS}"
mksquashfs "${SOURCE}" "${SQUASHFS}" -noappend -all-root -comp xz

# Build SquashApp
SQUASHAPP_FSSIZE="$(wc -c < "${SQUASHFS}")"
SQUASHAPP_SHA256="$(sha256sum -b "${SQUASHFS}" | cut -d ' ' -f 1)"

echo >&2 "Building ${SQUASHAPP}"
sed -e "s|^#!.*|#!${SQUASHAPP_SHELL}|" \
    -e "s|^SQUASHAPP_NAME=.*|SQUASHAPP_NAME=\"${SQUASHAPP_NAME}\"|" \
    -e "s|^SQUASHAPP_MAIN=.*|SQUASHAPP_MAIN=\"${SQUASHAPP_MAIN}\"|" \
    -e "s|^SQUASHAPP_FSSIZE=.*|SQUASHAPP_FSSIZE=\"${SQUASHAPP_FSSIZE}\"|" \
    -e "s|^SQUASHAPP_SHA256=.*|SQUASHAPP_SHA256=\"${SQUASHAPP_SHA256}\"|" \
    "${BASEDIR}"/lib/stub.sh | cat - "${BASEDIR}"/lib/squashapp.sh "${SQUASHFS}" > "${SQUASHAPP}"

rm "${SQUASHFS}"
chmod a+x "${SQUASHAPP}"

echo >&2 'Done'
