#!/bin/bash
# Build SquashFS app
set -e -u

BASEDIR="$(dirname "${BASH_SOURCE[0]}")"
RED="$(tput -T xterm setaf 1)"
GREEN="$(tput -T xterm setaf 2)"
RESET="$(tput -T xterm sgr0)"

function usage {
    log "Usage: $0 [--noembed] [-h|--help] <sourcedir> [<main>]"
    log "Options and arguments:"
    log "    --noembed      don't embed runtime into SquashApp"
    log "    -h, --help     show help (this text)"
    log
    log "    <sourcedir>    directory to build SquashApp from"
    log "    <main>         relative path of main executable (default: \`basename <sourcedir>\`)"
}

function log {
    echo >&2 "$*"
}

function status {
    echo >&2 "${GREEN}$*${RESET}"
}

function error {
    echo >&2 "${RED}ERROR: $*${RESET}"
}

function contains_executable {
    (cd "${1:?}" && [[ -n "$(find . -wholename ./"${2:?}" -executable)" ]])
}

# Flags
FLAG_NOEMBED=

for arg in "$@"; do
    case "${arg}" in
        --)
            shift
            break
            ;;
        --noembed)
            FLAG_NOEMBED=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        -*)
            error "Unknown flag $1"
            usage
            exit
            ;;
        *)
            continue
            ;;
    esac
    shift
done

if [[ $# -lt 1 || $# -gt 2 ]]; then
    usage
    exit 2
fi

# Check SOURCE is valid
SOURCE="$1"
if ! [[ -d "${SOURCE}" ]]; then
    error "${SOURCE} is not a directory"
    exit 1
fi

# Shell used for interpreting SquashApp
SQUASHAPP_SHELL=${SQUASHAPP_SHELL:-/bin/bash}
if ! [[ -x "${SQUASHAPP_SHELL}" ]]; then
    error "${SQUASHAPP_SHELL} is not a valid executable"
    exit 1
fi

# Search for main
NAME="$(basename -- "${SOURCE}")"
if [[ $# -gt 1 ]]; then
    MAIN_PATH=("$2")
else
    MAIN_PATH=(init bin/"${NAME}")
fi

for path in "${MAIN_PATH[@]}"; do
    if contains_executable "${SOURCE}" "${path}"; then
        SQUASHAPP_MAIN="${path}"
        break
    fi
done

if ! [[ -v SQUASHAPP_MAIN ]]; then
    error "No main found in "$1" (Tried ${MAIN_PATH[*]})"
    log "Note: <main> must be relative to <dir> (e.g. \"bin/${NAME}\")"
    exit 1
fi

# Build SquashFS
SQUASHFS="${NAME}.squash"

status "Building ${SQUASHFS}..."
mksquashfs "${SOURCE}" "${SQUASHFS}" -noappend -all-root -comp xz

# Build SquashApp
SQUASHAPP="${NAME}.run"
SQUASHAPP_FSSIZE="$(wc -c < "${SQUASHFS}")"
SQUASHAPP_SHA256="$(sha256sum -b "${SQUASHFS}" | cut -d ' ' -f 1)"

status "Building ${SQUASHAPP}..."
FRAGMENTS=()
if [[ -n "${FLAG_NOEMBED}" ]]; then
    INTERPRETER='/usr/bin/env squashapp_helper'
    FRAGMENTS+=( "${BASEDIR}"/lib/stub-runtime.sh )
else
    log 'Embedding runtime'
    INTERPRETER="${SQUASHAPP_SHELL}"
    FRAGMENTS+=( "${BASEDIR}"/lib/runtime.sh )
fi
FOOTER=$'\nexit 99\n# EOF'

{ cat - "${FRAGMENTS[@]}" <<EOF ; echo "${FOOTER}"; cat "${SQUASHFS}"; } > "${SQUASHAPP}"
#!${INTERPRETER}
# SquashFS app self-extractor
set -e -u

SQUASHAPP_MAIN='${SQUASHAPP_MAIN}'
SQUASHAPP_FSSIZE=${SQUASHAPP_FSSIZE}
SQUASHAPP_SHA256='${SQUASHAPP_SHA256}'
EOF

rm "${SQUASHFS}"
chmod a+x "${SQUASHAPP}"

du --apparent-size -h "${SQUASHAPP}"
log 'Done'
