#!/bin/bash
set -e -u

cd "$(dirname "${BASH_SOURCE[0]}")"

source lib.sh

for TESTFILE in *.test; do
    echo >&2 "Running ${TESTFILE}..."
    . "${TESTFILE}"
done

log
log "${#FAILED[@]} tests failed"
for failed in "${FAILED[@]}"; do
    log "- ${failed}"
done
