#!/bin/bash
set -e

cd "$(dirname "$0")"

source lib.sh

for TESTFILE in *.test; do
    echo >&2 "Running ${TESTFILE}..."
    . "${TESTFILE}"
done

log '\n%d tests failed' "${#FAILED[@]}"
for failed in "${FAILED[@]}"; do
    log '- %s' "${failed}"
done
